### ISSUE TITLE
【自荐】Negative Margin Matters: Understanding Margin in Few-shot Classification

### ISSUE THREAD

**Issue by bl0** [Duan-JM/awesome-papers-fewshot#12]
hi，自荐一波刚被 ECCV 2020 录用为 spotlight 的 paper：Negative Margin Matters: Understanding Margin in Few-shot Classification。
paper: https://arxiv.org/abs/2003.12060
code: https://github.com/bl0/negative-margin.few-shot

**Comment by Duan-JM** [comment]
嗨，恭喜拿到了 ECCV 2020 的 spotlight 🎉，也十分感谢大佬关注了这边的仓库 
这两天我就把他加进去～如果方便的话要是能用简单两句话概括下论文就更好啦。

**Comment by bl0** [comment]
Introduces a negative margin loss to metric learning based few-shot learning methods and achieves state-of-the-art accuracy. To understand why the negative margin loss performs well, we provide both the intuitive and theoretical analysis.

**Comment by Duan-JM** [comment]
Done~

**Comment by bl0** [comment]
Thanks.

**Comment by yty121** [comment]
作者您好，您的miniImagenet数据集下载不了，我自己下载的版本好像优点问题，用自己的数据集后json也出了问题现在还没有解决，请问一下可以给个你的数据集的地址吗？

**Comment by yty121** [comment]
或者给一下你的miniimagenet数据集的目录结构也可以，从我的目录结构来运行，需要修改的代码比较多.
1972434390@qq.com  20205227079@stu.suda.edu.cn 这两个是我的邮箱，如果可以的话，将会非常感谢.
