### ISSUE TITLE
Please add an ICCV'21 paper

### ISSUE THREAD

**Issue by dahyun-kang** [Duan-JM/awesome-papers-fewshot#14]
Hello,

Would you please include "Relational Embedding for Few-Shot Classification" (https://arxiv.org/abs/2108.09666) as well as its code (https://github.com/dahyun-kang/renet) in the "Few-shot classification" category? The paper is accepted at ICCV 2021.

They propose to learn relational patterns from self-correlation within an image representation and cross-correlation between two image representations to form relational embedding.

Have a great day! :smiley:

Best,
Dahyun

**Comment by Duan-JM** [comment]
Hi,

Thanks for recommending your awesome paper~ I have added it to "Few-shot classification" category according to  commit#4b2ef62.

Have a nice day!
Duan-JM
