### ISSUE TITLE
Please add a CVPR'22 paper

### ISSUE THREAD

**Issue by dahyun-kang** [Duan-JM/awesome-papers-fewshot#16]
Hello,

Would you please include "Integrative Few-Shot Learning for Classification and Segmentation" in the "Few-shot classification" and "Few-shot segmentation" category?  ([paper](https://arxiv.org/abs/2203.15712), [code](https://github.com/dahyun-kang/ifsl)) The paper is accepted at CVPR 2022.

They propose an integrative task of few-shot classification and segmentation (FS-CS) that aims to both classify and segment target objects in a query image when the target classes are given with a few examples.

Have a great day! 😃

Best,
Dahyun

**Comment by Duan-JM** [comment]
Sry replying late, I have updated it to segementation category.
