### ISSUE TITLE
few-shot papers

### ISSUE THREAD

**Issue by Bryce1010** [Duan-JM/awesome-papers-fewshot#6]
Hi, I'm new to this area, your summarize is really good. 
And I'm maintaining another "[awesome-fewshot](https://github.com/Bryce1010/Awesome-Few-shot)" including almost all  recent papers about few-shot. It's available for anyone to use, I hope my repository can be helpful to this good summary.
Thank you, Keep updating!

**Comment by Duan-JM** [comment]
Hi there, I am very glad to see someone still have interest in my repo. It can be great that we can maintain this repo together and turn this repo into a discussion playground for all people interest in few-shot.
